### ISSUE TITLE
Multiple episodes support error

### ISSUE THREAD

**Issue by motyafl** [sweetbbak/toru#11]
Okay, thank you! I will try to build it myself, I just wanted you to know about it.

_Originally posted by @motyafl in https://github.com/sweetbbak/toru/issues/10#issuecomment-1994129017_

I built it and was trying to test the episodes support, but it just doesn't work. It doesn't give me a choise what episode to stream. I checked, my torrent has multiple media files, but it doesn't work.

**Comment by sweetbbak** [comment]
alright, I will try another multimedia torrent today and check it out.

**Comment by 0azis** [comment]
I am author of that commit. I also checked that and it works fine on my build. Are you sure, that you built latest possible version? And if that, can you describe how you stream your torrent file?

**Comment by sweetbbak** [comment]
closed with ae5308909e76c006d8ca121d2061853ecaeb8df6
