### ISSUE TITLE
Add the ability to use proxy site of syaa

### ISSUE THREAD

**Issue by zuranota** [sweetbbak/toru#2]
Nyaa.si is banned my country. It would be nice to have the feature to add the proxy site in the list manually without getting my hands dirty in code. 

This is the output right now.
`2024/02/15 18:54:48 error getting the nyaa page: error requesting results: Get "https://nyaa.si?c=1_2&f=0&o=desc&p=1&q=one+piece&s=id":`

**Comment by sweetbbak** [comment]
Yea, that is important. Someone had also mentioned a kill switch so I will look into what that will take. Im guessing it shouldn't be too complicated but I'll have to see what is different and run some testing.

**Comment by sweetbbak** [comment]
Im testing this in the "dev" branch, if you want you can try it out by checking out that branch and building from source and then running:
```sh
./toru search --proxy "https://nyaa.iss.ink/" -i
```
I still have a lot of testing to do and Im thinking about creating a better interface for other sources so people can build them if they want or easily modify them.

**Comment by zuranota** [comment]
I can not build it. It is showing :
`no Go files in /home/user/github/toru`
I have switched to dev branch and i have Go installed.

**Comment by sweetbbak** [comment]
use the justfile or makefile by running "just" or "make build" or "go build -o toru ./cmd/toru"
