### ISSUE TITLE
Please create a release for the v0.3.2 tag

### ISSUE THREAD

**Issue by alexpdp7** [sweetbbak/toru#26]
I have [a tool to download binaries from GitHub releases](https://github.com/alexpdp7/ubpkg/), but it detects the latest release by searching for the latest tag. Because the `v0.3.2` tag exists, but only the `v0.3.1` release exists, it fails.

(I will add specific version downloading so it can download Toru, though. edit: if you are curious, `ubpkg toru --version v0.3.1` now works.)

**Comment by sweetbbak** [comment]
Cool tool! I made a release for this tag and I'm working on a github action so that when any tag is pushed it will just build and release automatically, so this shouldn't be a problem again.

**Comment by alexpdp7** [comment]
Cool, now `ubpkg toru` straight works. Thanks, closing!
