### ISSUE TITLE
Incorrect episode selection?

### ISSUE THREAD

**Issue by ProggerX** [sweetbbak/toru#27]
When i choose one episode from torrent from nyaa, wrong episode plays
my english is very bad =(

**Comment by ProggerX** [comment]
it's harmful and i can't find another tool like toru

**Comment by sweetbbak** [comment]
No worries. That would definitely be bad. Do you think you could show me an example video/image? or maybe tell me what anime, episode and provider that has this issue so I can look at it?

**Comment by ProggerX** [comment]
> No worries. That would definitely be bad. Do you think you could show me an example video/image? or maybe tell me what anime, episode and provider that has this issue so I can look at it?

I will show video today, but later
Also I tried different torrents and anime(s?)

**Comment by ProggerX** [comment]
But I can say that bocchi the rock from denisplay (or densiplay, I don't remember) didn't work

**Comment by ProggerX** [comment]
Also, I was using "nyaa.iss.ink" proxy

**Comment by sweetbbak** [comment]
ok gotcha. I'll take a look and see what I find

**Comment by ProggerX** [comment]
It's will be awesome if it is fixed :pray:

**Comment by ProggerX** [comment]
I noticed interesting thing!
When i choose EP 3, EP 10 plays
And when i choose EP 2, EP 11 plays
anime consists of 12 episodes
So i think this issue is connected to this commit maybe: https://github.com/sweetbbak/toru/commit/c8c7479c63627c9250ec67d3f438b4b019e63792
@sweetbbak what do you think?

**Comment by ProggerX** [comment]
I will try to explore code and make PR with fix

**Comment by ProggerX** [comment]
I found a solution, I will create a PR within an hour

**Comment by ProggerX** [comment]
Created PR, closing this issue
