### ISSUE TITLE
Play video directly from magnet link

### ISSUE THREAD

**Issue by Amrit-codes** [sweetbbak/toru#3]
Is it possible to directly open a torrent or magnet file by giving it an argument?

**Comment by sweetbbak** [comment]
if you want to stream from a torrent file, magnet or torrent file URL, you would do something like this:
```sh
# you can specify it explicitly
toru stream --torrent ~/Downloads/cool_video.torrent
# a magnet link
toru stream --magnet='magnet:?xt=urn:btih...'

# or you can let toru infer whether its a url, magnet or file by putting one of these as a trailing argument 
toru stream ./cool_video.torrent
toru stream 'magnet:?xt=urn:btih...'
toru stream https://example.net/cool_video.torrent
```

**Comment by Amrit-codes** [comment]
It would be nice to have a `--help` flag included for such issues

**Comment by sweetbbak** [comment]
toru stream --help
you can tack on --help to any of the main commands as well as the base command. Im also working on a man page with examples and an easy way to install that for users
