### ISSUE TITLE
Nix Package

### ISSUE THREAD

**Issue by W-Y-R** [sweetbbak/toru#5]
# Context
I'd like to inform you that I have finished the nix package for the software. Unfortunately, I cannot merge it currently due to a dependency error within the anacrolix/torrent repository (see GitHub issue: https://github.com/anacrolix/torrent/issues/900). Please consider updating the mod dependencies once the issue has been resolved.

# Error
Any command will just output `"error creating a new torrent client: subsequent listen: listen tcp6 :42069: socket: address family not supported by protocol"`.

**Comment by sweetbbak** [comment]
Thank you! I will keep an eye on it, it seems like there is a potential fix already in the works but if not I'll look into using the workaround mentioned and disable ipv6 until it is fixed.

I'm wondering if this is also why things aren't working on Termux. It seems likely.
