### ISSUE TITLE
Port already in use error.

### ISSUE THREAD

**Issue by kotenok2000** [sweetbbak/toru#6]
2024/03/09 17:06:29 error creating a new torrent client: first listen: listen tcp4 :42069: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

I have lantern using this port.

**Comment by sweetbbak** [comment]
Thanks for the issue, I overlooked adding that as an option. I still need to do more testing but I pushed a fix to main lol and added the option "--torrent-port" Im trying to work on some consistency since the torrent lib needs a range of tcp and udp ports.
