### ISSUE TITLE
Blocked in Russia

### ISSUE THREAD

**Issue by 0azis** [sweetbbak/toru#8]
Unfortunately, the nyaa torrent tracker is blocked in Russia. How about adding new trackers here?
I sent a request to friends in Discord to discuss this in more detail, I can offer my help.

**Comment by sweetbbak** [comment]
For sure. You can also try one of the proxy mirror sites with ```--proxy=nyaa.iss.ink``` or something similar. But I am also open to adding more trackers and a better interface so that people can write tracker libraries that easily plug into toru

**Comment by 0azis** [comment]
Okay, great! 
I also would like to ask, do you want to add support for movies of other genres, music, and so on in the future, or will you leave toru only for anime?
